---
title: A quick chronicle demo 
date: "`r Sys.Date()`" 

output: pdf_document
params:
  set_static: TRUE
  figure_width: 9
  figure_height: 5
  plot_palette: !r c()
  plot_palette_generator: 'plasma'
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(chronicle)
# If you want this report to be reproducible, add all the libraries, data
# loading and preprocessing code into this chunk before knitting.
```


# This is the output of a chronicle call

Each element has been added through an `add_*` function.

# A glimpse of the iris dataset
```{r, echo=FALSE, message=FALSE, warning=FALSE}
knitr::kable(head(iris))
```

## Distribution of Sepal.Length by Species
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=params$figure_width, fig.height=params$figure_height}
chronicle::make_raincloud(dt = iris,
                          value = 'Sepal.Length',
                          groups = 'Species',
                          adjust = 0.5,
                          include_boxplot = TRUE,
                          include_mean = FALSE,
                          include_median = TRUE,
                          force_all_jitter_obs = FALSE,
                          ggtheme = 'minimal',
                          plot_palette = params$plot_palette,
                          plot_palette_generator = params$plot_palette_generator,
                          static = params$set_static)
```

## Petal.Width vs Petal.Length by Species
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=params$figure_width, fig.height=params$figure_height}
chronicle::make_scatterplot(dt = iris,
                            x = 'Petal.Width',
                            y = 'Petal.Length',
                            groups = 'Species',
                            plot_palette = params$plot_palette,
                            plot_palette_generator = params$plot_palette_generator,
                            static = params$set_static)
```
